/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 macbookpro.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF, OrthographicCamera } from '@react-three/drei'

export function Model2(props) {
  const { nodes, materials } = useGLTF('./macbookpro.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[-15.425, 162.722, -212.286]} rotation={[-2.412, -0.457, 3.117]} scale={0.392}>
          <group position={[-1.273, -436.608, -17.856]} scale={[1, 1, 1.002]}>
            <group position={[-6.964, 478.108, 16.318]} scale={[1.957, 1.957, 1089621.131]}>
              <mesh geometry={nodes.logo_apple_1.geometry} material={materials['default']} position={[-22.723, 24.789, 0]} scale={[0.094, 0.094, 0]} />
              <mesh geometry={nodes.logo_apple_2.geometry} material={materials['default']} position={[0.139, 47.161, 0]} scale={[0.094, 0.094, 0]} />
            </group>
            <mesh geometry={nodes.connector.geometry} material={materials['default']} position={[1.273, -20.522, -5.615]} rotation={[-Math.PI, 0, -Math.PI]} scale={2.069} />
            <mesh geometry={nodes.screen_1.geometry} material={materials['default']} position={[669.198, 44.158, 0.656]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.899, 0.9, 0.9]} />
            <mesh geometry={nodes.green_light.geometry} material={materials['default']} position={[-25.412, 906.024, 0.612]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.818, 0.81, 0.922]} />
            <mesh geometry={nodes.black_border_notch_screen.geometry} material={materials['default']} position={[691.334, 915.76, 0.966]} rotation={[-Math.PI, 0, Math.PI]} scale={[0.902, 0.902, 1.004]} />
            <mesh geometry={nodes.grey_border_creen.geometry} material={materials['default']} position={[0.451, 448.36, 9.162]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.902, 0.902, 1.004]} />
            <mesh geometry={nodes.Rectangle_1.geometry} material={materials['default']} position={[0, 448.36, 15.068]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.902, 0.902, 1.004]} />
            <mesh geometry={nodes.metalic_screen.geometry} material={materials['default']} position={[0, 448.36, 10.166]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.902, 0.902, 1.004]} />
            <mesh geometry={nodes.camera.geometry} material={materials['default']} position={[-3.459, 906.024, 0.612]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.818, 0.81, 0.922]} />
            <mesh geometry={nodes.border_black_camera.geometry} material={materials['default']} position={[-3.459, 906.024, 0.841]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.818, 0.81, 0.922]} />
          </group>
          <group position={[-56.341, -457.519, -546.112]}>
            <group position={[5.418, -7.126, -0.405]} rotation={[-Math.PI, 0, -Math.PI]}>
              <mesh geometry={nodes.base_2.geometry} material={materials['default']} position={[10.976, 13.354, 134.945]} />
            </group>
            <group position={[1.277, 32.071, 180.03]} rotation={[-Math.PI, 0, -Math.PI]}>
              <mesh geometry={nodes.Rectangle_2.geometry} material={materials['default']} position={[585.274, 0.305, -16.442]} rotation={[-Math.PI / 2, 0, Math.PI]} />
              <mesh geometry={nodes.Rectangle_3.geometry} material={materials['default']} position={[-697.577, 0.305, -16.442]} rotation={[-Math.PI / 2, 0, Math.PI]} />
            </group>
            <group position={[51.909, -18.233, -11.947]} rotation={[-Math.PI, 0, -Math.PI]}>
              <mesh geometry={nodes.Subdiv_3.geometry} material={materials['default']} position={[466.778, 3.425, -412.464]} rotation={[0, 0, -Math.PI]} scale={[-1.092, 1.146, 1.127]} />
              <mesh geometry={nodes.Subdiv_3_1.geometry} material={materials['default']} position={[466.778, -2.641, -412.464]} rotation={[0, 0, -Math.PI]} scale={[-1, 1.05, 1.033]} />
              <mesh geometry={nodes.Subdiv_3_2.geometry} material={materials['default']} position={[-466.778, 3.425, -412.464]} rotation={[0, 0, -Math.PI]} scale={[-1.092, 1.146, 1.127]} />
              <mesh geometry={nodes.Subdiv_3_3.geometry} material={materials['default']} position={[-463.996, -3.761, -412.392]} rotation={[0, 0, -Math.PI]} scale={[-1, 1.05, 1.033]} />
              <mesh geometry={nodes.Subdiv_2.geometry} material={materials['default']} position={[466.778, 3.425, 326.825]} rotation={[0, 0, -Math.PI]} scale={[-1.092, 1.146, 1.127]} />
              <mesh geometry={nodes.Subdiv_2_1.geometry} material={materials['default']} position={[466.778, -2.641, 326.825]} rotation={[0, 0, -Math.PI]} scale={[-1, 1.05, 1.033]} />
              <mesh geometry={nodes.Subdiv.geometry} material={materials['default']} position={[-466.778, 3.425, 326.825]} rotation={[0, 0, -Math.PI]} scale={[-1.092, 1.146, 1.127]} />
              <mesh geometry={nodes.Cylinder.geometry} material={materials['default']} position={[-466.778, -2.641, 326.825]} rotation={[0, 0, -Math.PI]} scale={[-1, 1.05, 1.033]} />
            </group>
            <group position={[57.789, 37.671, 198.94]} rotation={[-Math.PI, 0, -Math.PI]}>
              <group position={[-550.659, -9.042, 198.694]} rotation={[-Math.PI / 2, 0, 0]}>
                <mesh geometry={nodes.mesh_26_instance_1.geometry} material={materials['default']} />
                <mesh geometry={nodes.mesh_26_instance_2.geometry} material={materials['default']} position={[81, 0, 0]} />
                <mesh geometry={nodes.mesh_26_instance_3.geometry} material={materials['default']} position={[162, 0, 0]} />
              </group>
              <group position={[-364.399, -9.042, 120.028]} rotation={[-Math.PI / 2, 0, 0]}>
                <mesh geometry={nodes.mesh_27_instance_1.geometry} material={materials['default']} />
                <mesh geometry={nodes.mesh_27_instance_2.geometry} material={materials['default']} position={[81, 0, 0]} />
                <mesh geometry={nodes.mesh_27_instance_3.geometry} material={materials['default']} position={[162, 0, 0]} />
                <mesh geometry={nodes.mesh_27_instance_4.geometry} material={materials['default']} position={[243, 0, 0]} />
                <mesh geometry={nodes.mesh_27_instance_5.geometry} material={materials['default']} position={[324, 0, 0]} />
                <mesh geometry={nodes.mesh_27_instance_6.geometry} material={materials['default']} position={[405, 0, 0]} />
                <mesh geometry={nodes.mesh_27_instance_7.geometry} material={materials['default']} position={[486, 0, 0]} />
                <mesh geometry={nodes.mesh_27_instance_8.geometry} material={materials['default']} position={[567, 0, 0]} />
                <mesh geometry={nodes.mesh_27_instance_9.geometry} material={materials['default']} position={[648, 0, 0]} />
                <mesh geometry={nodes.mesh_27_instance_10.geometry} material={materials['default']} position={[729, 0, 0]} />
              </group>
              <group position={[-405.798, -9.042, 40.694]} rotation={[-Math.PI / 2, 0, 0]}>
                <mesh geometry={nodes.mesh_28_instance_1.geometry} material={materials['default']} />
                <mesh geometry={nodes.mesh_28_instance_2.geometry} material={materials['default']} position={[81, 0, 0]} />
                <mesh geometry={nodes.mesh_28_instance_3.geometry} material={materials['default']} position={[162, 0, 0]} />
                <mesh geometry={nodes.mesh_28_instance_4.geometry} material={materials['default']} position={[243, 0, 0]} />
                <mesh geometry={nodes.mesh_28_instance_5.geometry} material={materials['default']} position={[324, 0, 0]} />
                <mesh geometry={nodes.mesh_28_instance_6.geometry} material={materials['default']} position={[405, 0, 0]} />
                <mesh geometry={nodes.mesh_28_instance_7.geometry} material={materials['default']} position={[486, 0, 0]} />
                <mesh geometry={nodes.mesh_28_instance_8.geometry} material={materials['default']} position={[567, 0, 0]} />
                <mesh geometry={nodes.mesh_28_instance_9.geometry} material={materials['default']} position={[648, 0, 0]} />
                <mesh geometry={nodes.mesh_28_instance_10.geometry} material={materials['default']} position={[729, 0, 0]} />
                <mesh geometry={nodes.mesh_28_instance_11.geometry} material={materials['default']} position={[810, 0, 0]} />
              </group>
              <group position={[-429.326, -9.042, -40.639]} rotation={[-Math.PI / 2, 0, 0]}>
                <mesh geometry={nodes.mesh_29_instance_1.geometry} material={materials['default']} />
                <mesh geometry={nodes.mesh_29_instance_2.geometry} material={materials['default']} position={[81, 0, 0]} />
                <mesh geometry={nodes.mesh_29_instance_3.geometry} material={materials['default']} position={[162, 0, 0]} />
                <mesh geometry={nodes.mesh_29_instance_4.geometry} material={materials['default']} position={[243, 0, 0]} />
                <mesh geometry={nodes.mesh_29_instance_5.geometry} material={materials['default']} position={[324, 0, 0]} />
                <mesh geometry={nodes.mesh_29_instance_6.geometry} material={materials['default']} position={[405, 0, 0]} />
                <mesh geometry={nodes.mesh_29_instance_7.geometry} material={materials['default']} position={[486, 0, 0]} />
                <mesh geometry={nodes.mesh_29_instance_8.geometry} material={materials['default']} position={[567, 0, 0]} />
                <mesh geometry={nodes.mesh_29_instance_9.geometry} material={materials['default']} position={[648, 0, 0]} />
                <mesh geometry={nodes.mesh_29_instance_10.geometry} material={materials['default']} position={[729, 0, 0]} />
                <mesh geometry={nodes.mesh_29_instance_11.geometry} material={materials['default']} position={[810, 0, 0]} />
                <mesh geometry={nodes.mesh_29_instance_12.geometry} material={materials['default']} position={[891, 0, 0]} />
                <mesh geometry={nodes.mesh_29_instance_13.geometry} material={materials['default']} position={[972, 0, 0]} />
              </group>
              <group position={[-429.326, -9.042, -196.639]} rotation={[-Math.PI / 2, 0, 0]}>
                <mesh geometry={nodes.mesh_44_instance_1.geometry} material={materials['default']} />
                <mesh geometry={nodes.mesh_44_instance_2.geometry} material={materials['default']} position={[81, 0, 0]} />
                <mesh geometry={nodes.mesh_44_instance_3.geometry} material={materials['default']} position={[162, 0, 0]} />
                <mesh geometry={nodes.mesh_44_instance_4.geometry} material={materials['default']} position={[243, 0, 0]} />
                <mesh geometry={nodes.mesh_44_instance_5.geometry} material={materials['default']} position={[324, 0, 0]} />
                <mesh geometry={nodes.mesh_44_instance_6.geometry} material={materials['default']} position={[405, 0, 0]} />
                <mesh geometry={nodes.mesh_44_instance_7.geometry} material={materials['default']} position={[486, 0, 0]} />
                <mesh geometry={nodes.mesh_44_instance_8.geometry} material={materials['default']} position={[567, 0, 0]} />
                <mesh geometry={nodes.mesh_44_instance_9.geometry} material={materials['default']} position={[648, 0, 0]} />
                <mesh geometry={nodes.mesh_44_instance_10.geometry} material={materials['default']} position={[729, 0, 0]} />
                <mesh geometry={nodes.mesh_44_instance_11.geometry} material={materials['default']} position={[810, 0, 0]} />
                <mesh geometry={nodes.mesh_44_instance_12.geometry} material={materials['default']} position={[891, 0, 0]} />
                <mesh geometry={nodes.mesh_44_instance_13.geometry} material={materials['default']} position={[972, 0, 0]} />
              </group>
              <group position={[-549.326, -9.042, -118.989]} rotation={[-Math.PI / 2, 0, 0]}>
                <mesh geometry={nodes.mesh_45_instance_1.geometry} material={materials['default']} />
                <mesh geometry={nodes.mesh_45_instance_2.geometry} material={materials['default']} position={[81, 0, 0]} />
                <mesh geometry={nodes.mesh_45_instance_3.geometry} material={materials['default']} position={[162, 0, 0]} />
                <mesh geometry={nodes.mesh_45_instance_4.geometry} material={materials['default']} position={[243, 0, 0]} />
                <mesh geometry={nodes.mesh_45_instance_5.geometry} material={materials['default']} position={[324, 0, 0]} />
                <mesh geometry={nodes.mesh_45_instance_6.geometry} material={materials['default']} position={[405, 0, 0]} />
                <mesh geometry={nodes.mesh_45_instance_7.geometry} material={materials['default']} position={[486, 0, 0]} />
                <mesh geometry={nodes.mesh_45_instance_8.geometry} material={materials['default']} position={[567, 0, 0]} />
                <mesh geometry={nodes.mesh_45_instance_9.geometry} material={materials['default']} position={[648, 0, 0]} />
                <mesh geometry={nodes.mesh_45_instance_10.geometry} material={materials['default']} position={[729, 0, 0]} />
                <mesh geometry={nodes.mesh_45_instance_11.geometry} material={materials['default']} position={[810, 0, 0]} />
                <mesh geometry={nodes.mesh_45_instance_12.geometry} material={materials['default']} position={[891, 0, 0]} />
                <mesh geometry={nodes.mesh_45_instance_13.geometry} material={materials['default']} position={[972, 0, 0]} />
              </group>
              <mesh geometry={nodes.Torus.geometry} material={materials['default']} position={[542.483, -3.08, -197.924]} rotation={[-Math.PI / 2, 0, 0]} scale={1.167} />
              <mesh geometry={nodes.keybord_lign.geometry} material={materials['default']} position={[306.674, -9.042, 198.694]} rotation={[-Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.keybord_lign_1.geometry} material={materials['default']} position={[-550.659, -9.042, 198.694]} rotation={[-Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.keybord_lign_2.geometry} material={materials['default']} position={[-364.399, -9.042, 120.028]} rotation={[-Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.keybord_lign_3.geometry} material={materials['default']} position={[-405.798, -9.042, 40.694]} rotation={[-Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.keybord_lign_4.geometry} material={materials['default']} position={[-429.326, -9.042, -40.639]} rotation={[-Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.Rectangle_6.geometry} material={materials['default']} position={[-39.254, -9.042, 198.255]} rotation={[-Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.Rectangle_7.geometry} material={materials['default']} position={[214.76, -9.042, 198.255]} rotation={[-Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.Rectangle_5.geometry} material={materials['default']} position={[-293.933, -9.042, 198.255]} rotation={[-Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.Rectangle_14.geometry} material={materials['default']} position={[466.157, -8.966, 180.772]} rotation={[-Math.PI / 2, 0, 0]} scale={[1, 1, 2.667]} />
              <mesh geometry={nodes.Rectangle_13.geometry} material={materials['default']} position={[466.157, -8.966, 215.498]} rotation={[-Math.PI / 2, 0, 0]} scale={[1, 1, 2.667]} />
              <mesh geometry={nodes.Rectangle_12.geometry} material={materials['default']} position={[548.766, -8.966, 215.498]} rotation={[-Math.PI / 2, 0, 0]} scale={[1, 1, 2.667]} />
              <mesh geometry={nodes.Rectangle_11.geometry} material={materials['default']} position={[386.568, -8.966, 215.498]} rotation={[-Math.PI / 2, 0, 0]} scale={[1, 1, 2.667]} />
              <mesh geometry={nodes.Rectangle_8.geometry} material={materials['default']} position={[494.676, -9.042, 120.419]} rotation={[-Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.Rectangle_4.geometry} material={materials['default']} position={[-499.797, -9.042, 120.419]} rotation={[-Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.Rectangle_9.geometry} material={materials['default']} position={[513.917, -9.042, 40.905]} rotation={[-Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.Rectangle_3_1.geometry} material={materials['default']} position={[-519.297, -9.042, 40.905]} rotation={[-Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.Rectangle_10.geometry} material={materials['default']} position={[523.26, -9.042, -119.429]} rotation={[-Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.Rectangle_2_1.geometry} material={materials['default']} position={[-530.797, -9.042, -40.801]} rotation={[-Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.Rectangle_15.geometry} material={materials['default']} position={[-529.297, -9.042, -196.639]} rotation={[-Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.keybord_lign_5.geometry} material={materials['default']} position={[-429.326, -9.042, -196.639]} rotation={[-Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.keybord_lign_6.geometry} material={materials['default']} position={[-549.326, -9.042, -118.989]} rotation={[-Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.keyboard_1.geometry} material={materials['default']} position={[0, -7.703, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[1, 1, 2.159]} />
              <mesh geometry={nodes.mesh_25_instance_1.geometry} material={materials['default']} position={[306.674, -9.042, 198.694]} rotation={[-Math.PI / 2, 0, 0]} />
            </group>
            <group position={[-4.129, 34.514, -284.996]} rotation={[-Math.PI, 0, -Math.PI]}>
              <mesh geometry={nodes.trackpad_top.geometry} material={materials['default']} position={[-61.189, -1.672, -41.264]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.834, 0.835, 5]} />
              <mesh geometry={nodes.trackpad_border.geometry} material={materials['default']} position={[-61.189, -2.481, -41.264]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.834, 0.835, 5]} />
            </group>
            <group position={[-633.046, 12.571, 270.937]} rotation={[-Math.PI, 0, -Math.PI]}>
              <mesh geometry={nodes.Rectangle_9_1.geometry} material={materials['default']} position={[-2.047, -20.268, 425.433]} rotation={[Math.PI / 2, 1.276, -Math.PI / 2]} />
              <mesh geometry={nodes.Rectangle_10_1.geometry} material={materials['default']} position={[0, 0, -105.067]} rotation={[0, Math.PI / 2, 0]} />
              <mesh geometry={nodes.Rectangle_9_2.geometry} material={materials['default']} position={[0, 2.5, -26.067]} rotation={[0, Math.PI / 2, 0]} />
              <mesh geometry={nodes.Rectangle_8_1.geometry} material={materials['default']} position={[0, 2.945, 79.567]} rotation={[0, Math.PI / 2, 0]} />
            </group>
            <group position={[745.729, 14.036, 293.612]}>
              <mesh geometry={nodes.Rectangle_8_2.geometry} material={materials['default']} position={[-1.384, -18.907, -448.108]} rotation={[Math.PI / 2, 1.231, -Math.PI / 2]} />
              <mesh geometry={nodes.Rectangle_3_2.geometry} material={materials['default']} position={[0.772, 1.08, 83.997]} rotation={[0, Math.PI / 2, 0]} />
              <mesh geometry={nodes.Ellipse.geometry} material={materials['default']} position={[0.485, -0.08, -113.497]} rotation={[0, Math.PI / 2, 0]} />
              <mesh geometry={nodes.Rectangle_6_1.geometry} material={materials['default']} position={[0.485, 0.575, -58.939]} rotation={[0, Math.PI / 2, 0]} />
              <mesh geometry={nodes.Rectangle_5_1.geometry} material={materials['default']} position={[0.485, 0.575, 5.16]} rotation={[0, Math.PI / 2, 0]} />
              <mesh geometry={nodes.Rectangle_4_1.geometry} material={materials['default']} position={[0.485, 1.08, 83.997]} rotation={[0, Math.PI / 2, 0]} />
            </group>
            <mesh geometry={nodes.Cube.geometry} material={materials['default']} position={[56.341, 17.747, 516.407]} rotation={[-Math.PI, 0, -Math.PI]} scale={[2.069, 2.069, 2.074]} />
          </group>
          <pointLight intensity={1.9} decay={2} distance={2000} color="#d591ff" position={[-260.186, 737.205, 1655.588]} rotation={[-Math.PI, 0, -Math.PI]} scale={2.069} />
          <pointLight intensity={1.9} decay={2} distance={2000} color="#ffb9f7" position={[-285.397, -58.2, -10.105]} rotation={[-Math.PI, 0, -Math.PI]} scale={2.069} />
          <pointLight intensity={1.9} decay={2} distance={2000} color="#b76aff" position={[0, -58.2, -10.105]} rotation={[-Math.PI, 0, -Math.PI]} scale={2.069} />
        </group>
        <OrthographicCamera makeDefault={false} far={50000} near={0} position={[40.958, 1.219, 1000]}>
          <directionalLight intensity={0.6} decay={2} rotation={[-0.7, 0.648, 0.949]} />
        </OrthographicCamera>
        <OrthographicCamera makeDefault={false} far={100000} near={0} position={[0, 0, 1000]} />
        <mesh geometry={nodes.Rectangle.geometry} material={materials['default']} position={[0, -359.007, 20.522]} rotation={[-1.491, 0, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('./macbookpro.gltf')
