/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 updatedScene.gltf 
Author: jc1245 (https://sketchfab.com/jasperchui2007)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/macbook-pro-a2158f4d07c24861b268b170cb24c6d8
Title: Macbook Pro
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function MacBookModel(props) {
  const { nodes, materials } = useGLTF("./macbook/updatedScene.gltf");
  return (
    <group {...props} dispose={null}>
      <group
        position={[0, 0, 0.118]}
        rotation={[-1.824, 0, 0]}
        scale={[1, 1, 0.999]}
      >
        <mesh geometry={nodes.Object_19.geometry} material={materials.Metal} />
        <mesh
          geometry={nodes.Object_20.geometry}
          material={materials["Material.010"]}
        />
        <mesh
          geometry={nodes.Object_21.geometry}
          material={materials["Material.008"]}
        />
        <mesh
          geometry={nodes.Object_22.geometry}
          material={materials.Material}
        />
        <mesh
          geometry={nodes.Object_23.geometry}
          material={materials["SVGMat.006"]}
        />
        <mesh
          geometry={nodes.Object_25.geometry}
          material={materials["Material.009"]}
          position={[0, 0.005, 0.122]}
          rotation={[-Math.PI, 0, 0]}
          scale={[0.166, 0.165, 0.104]}
        />
      </group>
      <mesh geometry={nodes.Object_4.geometry} material={materials.Metal} />
      <mesh geometry={nodes.Object_5.geometry} material={materials.Metal} />
      <mesh
        geometry={nodes.Object_6.geometry}
        material={materials["Material.002"]}
      />
      <mesh
        geometry={nodes.Object_7.geometry}
        material={materials["Material.003"]}
      />
      <mesh
        geometry={nodes.Object_8.geometry}
        material={materials["Material.007"]}
      />
      <mesh
        geometry={nodes.Object_9.geometry}
        material={materials["Material.006"]}
      />
      <mesh
        geometry={nodes.Object_10.geometry}
        material={materials["Material.005"]}
      />
      <mesh
        geometry={nodes.Object_11.geometry}
        material={materials["Material.001"]}
      />
      <mesh
        geometry={nodes.Object_12.geometry}
        material={materials["Material.001"]}
      />
      <mesh
        geometry={nodes.Object_13.geometry}
        material={materials["Material.001"]}
      />
      <mesh
        geometry={nodes.Object_14.geometry}
        material={materials["Material.001"]}
      />
      <mesh
        geometry={nodes.Object_15.geometry}
        material={materials["Material.004"]}
      />
      <mesh
        geometry={nodes.Object_16.geometry}
        material={materials["Material.013"]}
      />
      <mesh
        geometry={nodes.Object_17.geometry}
        material={materials["Material.013"]}
      />
    </group>
  );
}

useGLTF.preload("./macbook/updatedScene.gltf");
